---
- name: Get ClickHouse service status
  command: service clickhouse-server status
  register: service_status
  changed_when: no
  ignore_errors: yes

- name: Verify ClickHouse is running
  assert:
    that:
      - "'Active: ' in service_status.stdout"
