---
- name: Config | Set ClickHouse configuration file
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0664"
  notify: Restart ClickHouse

- name: Config | Logging configuration
  template:
    src: log-level.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse

- name: Config | Kafka <-> CH interface
  template:
    src: kafka.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/kafka.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse

- name: Config | Generate users config
  template:
    src: users.xml.j2
    dest: "{{ clickhouse_conf_dir }}/users.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"

- name: Config | Zookeeper config.
  template:
    src: zookeeper.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/zookeeper.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse

- name: Config | Macros config.
  template:
    src: macros.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/macros.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"

- name: Config | CH clusters config.
  template:
    src: clusters.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/clusters.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"


- name: Config | CH listen_host config.
  template:
    src: listen_host.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/listen_host.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"

- name: Config | CH display_name config.
  template:
    src: display_name.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/display_name.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
