---
- name: Config | Set ClickHouse configuration file
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0664"
  notify: Restart ClickHouse
  tags:
    - ch-config

- name: Config | Logging configuration
  template:
    src: log-level.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse
  tags:
    - ch-logging-config

- name: Config | Kafka <-> CH interface
  template:
    src: kafka.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/kafka.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse
  tags:
    - ch-kafka-cfg

- name: Config | Generate users config
  template:
    src: users.xml.j2
    dest: "{{ clickhouse_conf_dir }}/users.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  tags:
    - ch-usr-cfg

- name: Config | Zookeeper config.
  template:
    src: zookeeper.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/zookeeper.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse
  tags:
    - ch-zk-cfg

- name: Config | Macros config.
  template:
    src: macros.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/macros.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  tags:
    - ch-macros-cfg

- name: Config | CH instances config.
  template:
    src: instances.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/instances.xml"
    mode: "0664"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  tags:
    - ch-instances-cfg