---
- name: Create ClickHouse configuration file
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.xml"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    mode: "0664"
  notify: Restart ClickHouse

- name: Define CH log level
  template:
    src: log-level.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
    mode: "0444"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse

- name: CH credentials to connect to Kafka
  template:
    src: kafka.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/kafka.xml"
    mode: "0444"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse

- name: Config | Generate users config
  template:
    src: users.xml.j2
    dest: "{{ clickhouse_conf_dir }}/{{ clickhouse_users_config }}"
    mode: "0644"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  notify: Restart ClickHouse
