---
- name: Create ClickHouse configuration file
  template:
    src: config.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.xml"
    owner: root
    group: root
    mode: '0664'

- name: Define CH log level
  template:
    src: log-level.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
    mode: '0444'
  notify: Restart ClickHouse

- name: CH credentials to connect to Kafka
  template:
    src: kafka.xml.j2
    dest: "{{ clickhouse_conf_dir }}/config.d/kafka.xml"
    mode: '0444'
  notify: Restart ClickHouse
