---
- name: Create ClickHouse group
  group:
    name: "{{ clickhouse_group }}"
    state: present

- name: Create ClickHouse user
  user:
    name: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
    state: present
    createhome: no

- name: Add the APT Key for ClickHouse.
  apt_key:
    keyserver: "{{ clickhouse_key_server }}"
    id: E0C56BD4
    state: present

- name: Add ClickHouse APT sources
  apt_repository:
    repo: deb https://repo.clickhouse.tech/deb/stable/ main/
    state: present

- name: Install ClickHouse
  apt:
    pkg:
      - clickhouse-server
      - clickhouse-client
  notify: Enable ClickHouse

- name: Create non sensitive ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  loop:
    - "{{ clickhouse_conf_dir }}"
    - "{{ clickhouse_log_path }}"

- name: Create sensitive ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  loop:
    - "{{ clickhouse_path }}"
    - "{{ clickhouse_user_files_path }}"
    - "{{ clickhouse_access_control_path }}"
    - "{{ clickhouse_tmp_path }}"
