---
- name: Enable ClickHouse
  systemd:
    name: clickhouse-server
    enabled: yes
    state: started
    daemon_reload: yes
  listen: Update ClickHouse

- name: Restart ClickHouse
  systemd:
    name: clickhouse-server
    state: restarted
  listen: Update ClickHouse

# yakovlev: need precise look
- name: Restart Keeper
  systemd:
    name: clickhouse-keeper
    state: restarted
  listen: Update Keeper