---
- name: Configure hosts
  hosts: all
  become: yes
#  vars:
#    clickhouse_conf_dir: "/etc/clickhouse-server"
#    clickhouse_logs_conf: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"
#    clickhouse_loglevel: "information"
  tasks:
    - name: Create database
      command: clickhouse-client --query "CREATE DATABASE IF NOT EXISTS molecule_tests"
      changed_when: no
    - name: Create table
      command: clickhouse-client --query "CREATE TABLE IF NOT EXISTS molecule_tests.insert_data(`id` UInt32, `City` String) ENGINE=TinyLog();"
      changed_when: no
    - name: Insert data into table, 1.
      command: clickhouse-client --query "INSERT INTO molecule_tests.insert_data VALUES(11, 'Rome');"
      changed_when: no
    - name: Insert data into table, 2.
      command: clickhouse-client --query "INSERT INTO molecule_tests.insert_data VALUES(33, 'Zagreb');"
      changed_when: no
# clickhouse-client --query "CREATE DATABASE IF NOT EXISTS molecule_tests"
# clickhouse-client --query 'CREATE TABLE molecule_tests.insert_data(`id` UInt32, `City` String) ENGINE=TinyLog();'
# clickhouse-client --query "INSERT INTO molecule_tests.insert_data VALUES(11, 'Rome');"
# clickhouse-client --query "INSERT INTO molecule_tests.insert_data VALUES(33, 'Zagreb');"
